# Generated by Django 6.0.5 on 2026-05-19 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aulas', '0001_initial'),
        ('estudiantes', '0001_initial'),
        ('horarios', '0001_initial'),
        ('materias', '0001_initial'),
        ('periodos', '0001_initial'),
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.aula')),
                ('estudiantes', models.ManyToManyField(to='estudiantes.estudiante')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.horario')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodos.periodo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesores.profesor')),
            ],
        ),
    ]
