# Generated by Django 6.0.5 on 2026-06-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_grupo_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
